language: node_js
node_js:
  -  dist: trusty
  - stable
before_script:
  - npm install -g @angular/cli
script:
  - ng build --prod --bh /Angular Front/
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $API_KEY_GITHUB
  keep-history: true
  target-branch: gh-pages
  local-dir: dist
  on:
    branch: master