language: node_js
node_js:
  - stable
script:
   - ng build --prod --bh /Angular-FrontEnd/
   - npm install -g @angular/cli
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $API_KEY_GITHUB
  keep-history: true
  target-branch: gh-pages
  local-dir: dist
  on:
    branch: master